baseURL = "https://www.dg-nlp.com"
languageCode = "en-ie"
title = "Daniel Gallagher"
theme = "digital-garden"
themesdir = "theme/"
copyright = "Daniel Gallagher Â©"


[params]
  name = "Daniel Gallagher"
  description = "Natural Language Processing"
  initials = "Daniel Gallagher"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/DanielGall500/"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/daniel-gallagher-a520161a3/"
    icon = "fab fa-linkedin-in"


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'